export const gridMock = [
  { x: 1, y: 1, isHitted: false, shipId: "" },
  { x: 2, y: 1, isHitted: false, shipId: "" },
  { x: 3, y: 1, isHitted: false, shipId: "" },
  { x: 4, y: 1, isHitted: false, shipId: "" },
  { x: 5, y: 1, isHitted: false, shipId: "" },
  { x: 6, y: 1, isHitted: false, shipId: "" },
  { x: 7, y: 1, isHitted: false, shipId: "" },
  { x: 8, y: 1, isHitted: false, shipId: "" },
  { x: 9, y: 1, isHitted: false, shipId: "" },
  { x: 10, y: 1, isHitted: false, shipId: "" },
  { x: 1, y: 2, isHitted: false, shipId: "" },
  { x: 2, y: 2, isHitted: false, shipId: "" },
  { x: 3, y: 2, isHitted: false, shipId: "" },
  { x: 4, y: 2, isHitted: false, shipId: "" },
  { x: 5, y: 2, isHitted: false, shipId: "" },
  { x: 6, y: 2, isHitted: false, shipId: "" },
  { x: 7, y: 2, isHitted: false, shipId: "" },
  { x: 8, y: 2, isHitted: false, shipId: "" },
  { x: 9, y: 2, isHitted: false, shipId: "" },
  { x: 10, y: 2, isHitted: false, shipId: "" },
  { x: 1, y: 3, isHitted: false, shipId: "" },
  { x: 2, y: 3, isHitted: false, shipId: "" },
  { x: 3, y: 3, isHitted: false, shipId: "" },
  { x: 4, y: 3, isHitted: false, shipId: "" },
  { x: 5, y: 3, isHitted: false, shipId: "" },
  { x: 6, y: 3, isHitted: false, shipId: "" },
  { x: 7, y: 3, isHitted: false, shipId: "" },
  { x: 8, y: 3, isHitted: false, shipId: "" },
  { x: 9, y: 3, isHitted: false, shipId: "" },
  { x: 10, y: 3, isHitted: false, shipId: "" },
  { x: 1, y: 4, isHitted: false, shipId: "" },
  { x: 2, y: 4, isHitted: false, shipId: "" },
  { x: 3, y: 4, isHitted: false, shipId: "" },
  { x: 4, y: 4, isHitted: false, shipId: "" },
  { x: 5, y: 4, isHitted: false, shipId: "" },
  { x: 6, y: 4, isHitted: false, shipId: "" },
  { x: 7, y: 4, isHitted: false, shipId: "" },
  { x: 8, y: 4, isHitted: false, shipId: "" },
  { x: 9, y: 4, isHitted: false, shipId: "" },
  { x: 10, y: 4, isHitted: false, shipId: "" },
  { x: 1, y: 5, isHitted: false, shipId: "" },
  { x: 2, y: 5, isHitted: false, shipId: "" },
  { x: 3, y: 5, isHitted: false, shipId: "" },
  { x: 4, y: 5, isHitted: false, shipId: "" },
  { x: 5, y: 5, isHitted: false, shipId: "" },
  { x: 6, y: 5, isHitted: false, shipId: "" },
  { x: 7, y: 5, isHitted: false, shipId: "" },
  { x: 8, y: 5, isHitted: false, shipId: "" },
  { x: 9, y: 5, isHitted: false, shipId: "" },
  { x: 10, y: 5, isHitted: false, shipId: "" },
  { x: 1, y: 6, isHitted: false, shipId: "" },
  { x: 2, y: 6, isHitted: false, shipId: "" },
  { x: 3, y: 6, isHitted: false, shipId: "" },
  { x: 4, y: 6, isHitted: false, shipId: "" },
  { x: 5, y: 6, isHitted: false, shipId: "" },
  { x: 6, y: 6, isHitted: false, shipId: "" },
  { x: 7, y: 6, isHitted: false, shipId: "" },
  { x: 8, y: 6, isHitted: false, shipId: "" },
  { x: 9, y: 6, isHitted: false, shipId: "" },
  { x: 10, y: 6, isHitted: false, shipId: "" },
  { x: 1, y: 7, isHitted: false, shipId: "" },
  { x: 2, y: 7, isHitted: false, shipId: "" },
  { x: 3, y: 7, isHitted: false, shipId: "" },
  { x: 4, y: 7, isHitted: false, shipId: "" },
  { x: 5, y: 7, isHitted: false, shipId: "" },
  { x: 6, y: 7, isHitted: false, shipId: "" },
  { x: 7, y: 7, isHitted: false, shipId: "" },
  { x: 8, y: 7, isHitted: false, shipId: "" },
  { x: 9, y: 7, isHitted: false, shipId: "" },
  { x: 10, y: 7, isHitted: false, shipId: "" },
  { x: 1, y: 8, isHitted: false, shipId: "" },
  { x: 2, y: 8, isHitted: false, shipId: "" },
  { x: 3, y: 8, isHitted: false, shipId: "" },
  { x: 4, y: 8, isHitted: false, shipId: "" },
  { x: 5, y: 8, isHitted: false, shipId: "" },
  { x: 6, y: 8, isHitted: false, shipId: "" },
  { x: 7, y: 8, isHitted: false, shipId: "" },
  { x: 8, y: 8, isHitted: false, shipId: "" },
  { x: 9, y: 8, isHitted: false, shipId: "" },
  { x: 10, y: 8, isHitted: false, shipId: "" },
  { x: 1, y: 9, isHitted: false, shipId: "" },
  { x: 2, y: 9, isHitted: false, shipId: "" },
  { x: 3, y: 9, isHitted: false, shipId: "" },
  { x: 4, y: 9, isHitted: false, shipId: "" },
  { x: 5, y: 9, isHitted: false, shipId: "" },
  { x: 6, y: 9, isHitted: false, shipId: "" },
  { x: 7, y: 9, isHitted: false, shipId: "" },
  { x: 8, y: 9, isHitted: false, shipId: "" },
  { x: 9, y: 9, isHitted: false, shipId: "" },
  { x: 10, y: 9, isHitted: false, shipId: "" },
  { x: 1, y: 10, isHitted: false, shipId: "" },
  { x: 2, y: 10, isHitted: false, shipId: "" },
  { x: 3, y: 10, isHitted: false, shipId: "" },
  { x: 4, y: 10, isHitted: false, shipId: "" },
  { x: 5, y: 10, isHitted: false, shipId: "" },
  { x: 6, y: 10, isHitted: false, shipId: "" },
  { x: 7, y: 10, isHitted: false, shipId: "" },
  { x: 8, y: 10, isHitted: false, shipId: "" },
  { x: 9, y: 10, isHitted: false, shipId: "" },
  { x: 10, y: 10, isHitted: false, shipId: "" },
];

export const shipMock1 = {
  coords: [
    { x: 1, y: 5 },
    { x: 1, y: 6 },
    { x: 1, y: 7 },
  ],
  id: 1,
  lenght: 3,
  hits: 0,
  sunk: false,
};
export const shipMock2 = {
  coords: [
    { x: 1, y: 1 },
    { x: 2, y: 1 },
    { x: 3, y: 1 },
  ],
  id: 2,
  lenght: 3,
  hits: 0,
  sunk: false,
};
export const shipMock3 = {
  coords: [
    { x: 3, y: 2 },
    { x: 4, y: 2 },
    { x: 5, y: 2 },
  ],
  id: 3,
  lenght: 3,
  hits: 0,
  sunk: false,
};
export const shipMock4 = {
  coords: [
    { x: 7, y: 3 },
    { x: 8, y: 3 },
    { x: 9, y: 3 },
  ],
  id: 4,
  lenght: 3,
  hits: 0,
  sunk: false,
};
export const shipMock5 = {
  coords: [
    { x: 2, y: 5 },
    { x: 2, y: 6 },
    { x: 2, y: 7 },
  ],
  id: 5,
  lenght: 3,
  hits: 0,
  sunk: false,
};
export const shipMock6 = {
  coords: [
    { x: 3, y: 1 },
    { x: 4, y: 1 },
    { x: 5, y: 1 },
  ],
  id: 6,
  lenght: 3,
  hits: 0,
  sunk: false,
};
export const shipMock7 = {
  coords: [
    { x: 3, y: 6 },
    { x: 4, y: 6 },
    { x: 5, y: 6 },
  ],
  id: 7,
  lenght: 3,
  hits: 0,
  sunk: false,
};
export const shipMock8 = {
  coords: [
    { x: 7, y: 9 },
    { x: 8, y: 9 },
    { x: 9, y: 9 },
  ],
  id: 8,
  lenght: 3,
  hits: 0,
  sunk: false,
};
